### ISSUE TITLE
Test fails on main on macos

### ISSUE THREAD

**Issue by mkmik** [influxdata/object_store_rs#49]
```console
$ cargo test
...
---- local::tests::test_list_root stdout ----
thread 'local::tests::test_list_root' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath { source: Canonicalize { path: "/.VolumeIcon.icns", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/local.rs:692:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    local::tests::test_list_root

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.30s
```

same commit works on linux

**Comment by mkmik** [comment]
Reproducer on Linux:

```console
$ uname
Linux
$ sudo ln -s /foo /bad
$ cargo test
---- local::tests::test_list_root stdout ----
thread 'local::tests::test_list_root' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath { source: Canonicalize { path: "/bad", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/local.rs:692:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    local::tests::test_list_root

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.23s

error: test failed, to rerun pass '--lib'
```

basically the problem is that in my mac (and possibly other macs), there is a broken symlink in the root dir.

```console
$ file /.VolumeIcon.icns
/.VolumeIcon.icns: broken symbolic link to System/Volumes/Data/.VolumeIcon.icns
```

**Comment by tustvold** [comment]
I intend to fix this by making the LocalFileSystem ignore broken soft links

**Comment by alamb** [comment]
Moved to https://github.com/apache/arrow-rs/issues/2174
